version: '3.5'

services:
  discovery-server:
    restart: always
    image: dantin/discovery-server:latest
    command: java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=docker -jar app.jar
    ports:
      - 8761:8761
  auth-server:
    restart: always
    image: dantin/auth-server:latest
    ports:
      - 9999:9999
    command: java -Dspring.profiles.active=docker -jar app.jar
    links:
      - "discovery-server"
    depends_on:
      - discovery-server
  product-service:
    restart: always
    image: dantin/product-service:latest
    command: java -Dspring.profiles.active=docker -jar app.jar
    links:
      - "discovery-server"
    depends_on:
      - discovery-server
