server:
  port: 8761
security:
  user:
    password: ${eureka.password} # Don't use a default password in a real app
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  password: ${SECURITY_USER_PASSWORD:password}

---
spring:
  profiles: peer # not standalone
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://user:${eureka.password}@127.0.0.1:8762/eureka/

---
spring:
  profiles: other # not standalone
server:
  port: 8762
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      default-zone: http://user:${eureka.password}@127.0.0.1:8761/eureka/

---
spring:
  profiles: local # connect to remote peer
eureka:
  instance:
    hostname: ${localhost.hostname:${localhost.ngrok}.ngrok.com}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
