server:
  port: 8761

security:
  user:
    password: ${eureka.password} # Don't use a default password in a real app

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false
  password: ${SECURITY_USER_PASSWORD:password}

---
spring:
  profiles: docker

eureka:
  instance:
    hostname: discovery-server
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:${eureka.password}@discovery-server:8761/eureka/
  server:
    enable-self-preservation: false

---
spring:
  profiles: docker2
eureka:
  instance:
    hostname: discovery2
  client:
    service-url:
      defaultZone: http://user:${eureka.password}@discovery-server:8761/eureka/
---
spring:
  profiles: peer # not standalone
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8762/eureka/
