server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  password: ${SECURITY_USER_PASSWORD:password}

---
# For development in Docker containers
spring:
  profiles: docker

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:${eureka.password}@discovery-server:8761/eureka/
