server:
  port: 0

gateway-port: 8765

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: webshop
      access-token-uri: http://localhost:${gateway-port}/api/auth/oauth/token
      user-authorization-uri: http://localhost:${gateway-port}/api/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:${gateway-port}/api/auth/api/member
      prefer-token-info: false

management:
  security:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  password: ${SECURITY_USER_PASSWORD:password}

logging:
  level:
    com.github.dantin: INFO

---
# For development in Docker containers
spring:
  profiles: docker
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:${eureka.password}@discovery-server:8761/eureka/
security:
  oauth2:
    client:
      access-token-uri: http://edge-server:${gateway-port}/api/auth/oauth/token
      user-authorization-uri: http://edge-server:${gateway-port}/api/auth/oauth/authorize
    resource:
      user-info-uri: http://edge-server:${gateway-port}/api/auth/api/member
