server:
  port: 0

gateway-port: 8765

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: webshop
      access-token-uri: http://localhost:${gateway-port}/api/auth/oauth/token
      user-authorization-uri: http://localhost:${gateway-port}/api/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:${gateway-port}/api/auth/api/member
      prefer-token-info: false

management:
  security:
    enabled: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registry-fetch-interval-seconds: 5

logging:
  level:
    com.github.dantin: INFO
