server:
  port: 8765

info:
  component: Zuul Server

endpoint:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignored-services: "*"
  prefix: /api
  add-proxy-headers: true
  routes:
    product:
      path: /product/**
      service-id: productapi
      sensitive-headers: "*"
    auth:
      path: /auth/**
      service-id: authserver
      sensitive-headers: "*"

security:
  oauth2:
    client:
      client-id: acme
      scope: webshop
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:${server.port}/auth/api/member
      prefer-token-info: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  password: ${SECURITY_USER_PASSWORD:password}

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

---
# For development in Docker containers
spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:${eureka.password}@discovery-server:8761/eureka/
