info:
  component: Zuul Server

endpoint:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    productapi: /product/**

eureka:
  instance:
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
